# HedgeForge Configuration Settings

# Simulation settings
simulation:
  n_simulations: 1000
  time_steps: 252
  dt: 0.003968  # 1/252
  seed: 42

# Optimization settings
optimization:
  risk_free_rate: 0.02
  target_return: null  # Set to specific value if needed
  max_position_size: 0.1
  min_position_size: 0.0
  risk_aversion: 1.0
  confidence_level: 0.95

# Backtesting settings
backtest:
  lookback_period: 756  # 3 years
  rebalance_frequency: 21  # Monthly
  transaction_cost: 0.001
  benchmark: "SPY"  # Default benchmark

# Risk settings
risk:
  confidence_level: 0.95
  var_method: "historical"  # historical or parametric
  rolling_window: 252

# Forecasting settings
forecasting:
  method: "historical_mean"  # historical_mean, shrinkage, ml
  lookback_periods: 252
  target_horizon: 21
  shrinkage_parameter: 0.5

# ML model settings (for forecasting)
ml_models:
  ridge:
    alpha: 1.0
  lasso:
    alpha: 0.01
  random_forest:
    n_estimators: 100
    max_depth: 10

# Constraints settings
constraints:
  long_only: true
  max_position_size: 0.1
  min_position_size: 0.0
  max_turnover: 0.2
  max_leverage: 1.0

# Regulatory constraints
regulatory:
  ucits:
    max_single_position: 0.05
    max_aggregate_large: 0.4
    max_aggregate_small: 0.6
  40_act:
    max_single_position: 0.25
    max_sector: 0.25
    diversification_requirement: 0.75

# Data settings
data:
  start_date: "2020-01-01"
  end_date: null  # Use current date if null
  frequency: "D"  # Daily
  min_data_points: 252

# Logging settings
logging:
  level: "INFO"
  file: "logs/hedgeforge.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Output settings
output:
  save_results: true
  output_dir: "data/processed"
  plot_format: "png"
  dpi: 300 